version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns: ['@angular/*', 'ng-packagr', 'typescript', 'zone.js']
      dev:
        dependency-type: development
    ignore:
      - dependency-name: '@angular/*'
        update-types: ['version-update:semver-major']
      - dependency-name: ng-packagr
        update-types: ['version-update:semver-major']
      - dependency-name: typescript
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: zone.js
        update-types: ['version-update:semver-minor']
      - dependency-name: jasmine-core
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/jasmine'
        update-types: ['version-update:semver-major']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
